name: Manually trigger an Azure Machine Learning job

on:
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Submit Azure ML Job
      run: |
        az ml job create \
          -f src/job.yml \
          -c ${{secrets.AZUREML_COMPUTE_TARGET}} \
          -e ${{secrets.AZUREML_ENVIRONMENT_NAME}} \
          -n ${{secrets.AZUREML_EXPERIMENT_NAME}} \
          -d ${{secrets.AZUREML_JOB_DESCRIPTION}}
